### PR TITLE
fix(api): GET application should return details info

### LINKED ISSUE #356: [Bug]: GET /applications/{name} return empty object
## Describe the bug:

When call GET /applications/{name}. it return `{}`

## Expected behavior:

Expected response is 

```json
{
  "status": "success",
  "data": {
    "name": "xxx",
    "path": "xxx",
    "ref": "xxx",
    "timestamp": "xxxx"
  }
}
```

## Environment;

- Operating System(s): Linux/macOS/Windows [Variant and Version]
- Browser: Firefox/Chrome/Safari [Version] / Other (please specify)

### PR DESCRIPTION
**Pull request by kunyan**
## Closes / Fixes / Resolves
Fix #356 

## Screenshot(s)

<details>
<summary>View Screenshots</summary>

</details>

### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [x] Does the change have appropriate unit tests?
- [x] Did tests pass?
- [ ] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [ ] Was this feature demo'd and the design review approved?

### CODE REVIEW

File: packages/api/controllers/application.js [hunk 1]
```diff
@@ -14,9 +15,13 @@ module.exports.list = async (req, res, next) => {
...
 module.exports.get = async (req, res) => {
   const userId = getUserUUID(req);
-  const { name } = req.param;
-  const application = Application.findOne({ name, userId });
-  res.send(application);
+  const { name } = req.params;
+  const application = await Application.findOne({ name, userId });
+  const appPath = application.get("path");
+  const spaDir = common.flatpath.toDir(appPath);
+  console.log(spaDir);
```
Comment (sayak-sarkar) [inline packages/api/controllers/application.js:22]: Is this log needed?

**Comment by kunyan** [comment]
removed `console.log`. merged this PR
