### PR TITLE
fix(#475): Added path validation before publishing

### LINKED ISSUE #475: [Bug]: Prevent deploying application to wrong paths
## Describe the bug:
I was able to deploy the application to a wrong path like the one shown below using SPAShip CLI:
Screenshot 2020-05-17 at 3 07 21 PM

## Steps to reproduce:
1. Create a spaship.yaml file like the one below:
```
name: CertificationWorkflow
path: demoapp123
single: true
```
2. run `spaship deploy` command

## Expected behavior:
`spaship deploy` command should throw an error if the path is not prefixed with '/`

## Screenshots:
n/a

## Environment;
dev
- Operating System(s): Mac OS Catalina 10.15.4 (19E287)
- Browser: Chrome Version 81.0.4044.138 (Official Build) (64-bit)

## Tell us more about your product/project and timeline to help prioritize this issue:
* CLI

## Additional context
n/a

### PR DESCRIPTION
**Pull request by gautamkrishnar**
## Closes / Fixes / Resolves
#475 

## Explain the feature/fix
Added `startsWith('/')` check for path to prevent deploying the application to wrong paths. CLI will automatically prefix the path with a `/`.

## Does this PR introduce a breaking change
No

## Screenshot(s)

<details>
<summary>View Screenshots</summary>
</details>

### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [ ] Does the change have appropriate unit tests?
- [x] Did tests pass?
- [x] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [x] Was this feature demo'd and the design review approved?

### CODE REVIEW

File: packages/cli/src/commands/deploy.js [hunk 1]
```diff
@@ -36,6 +36,9 @@ class DeployCommand extends Command {
     if (!path) {
       this.error("Please define your app path in your package.json or use init to create spaship.yaml ");
     }
+    if (!path.startsWith("/")) {
+      this.error("Path should be prefixed with `/`, got: " + path);
```
Comment (kunyan) [inline packages/cli/src/commands/deploy.js:40]: Why not add a `/` and without throw error ?

Comment (kunyan) [reply packages/cli/src/commands/deploy.js:40]: https://github.com/spaship/spaship/issues/432

Comment (gautamkrishnar) [reply packages/cli/src/commands/deploy.js]: @kunyan  made the changes
