### PR TITLE
fix(api): avoid overwrite exists .htaccess

### LINKED ISSUE #523: [Bug]: Generated .htaccess overwrite the exist .htaccess in SPA archive
## Describe the bug:

The API will generate `.htaccess` to help the simple SPA which need support single page feature
https://github.com/spaship/spaship/blob/ec86abf7e6fa575b74ce24fd3e610544536bffa6/packages/api/services/deployService.js#L70

However, if the SPA already has a `.htaccess` file, the API will overwrite it

## Environment;

- Operating System(s): Linux/macOS/Windows [Variant and Version]
- Browser: Firefox/Chrome/Safari [Version] / Other (please specify)

### PR DESCRIPTION
**Pull request by kunyan**
## Closes / Fixes / Resolves

Fix #523 

## Screenshot(s)

<details>
<summary>View Screenshots</summary>

</details>

### Ready-for-merge Checklist

- [ ] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [ ] Does the change have appropriate unit tests?
- [ ] Did tests pass?
- [ ] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [ ] Was this feature demo'd and the design review approved?

### CODE REVIEW

File: packages/api/services/deployService.js [hunk 1]
```diff
@@ -66,6 +66,15 @@ async function deploy({ name, spaArchive, appPath, ref } = {}) {
     await fileService.write(yamlFilePath, { ref });
   }
 
+  try {
+    const htaccessPath = path.join(tmpDir, ".htaccess");
+    if (!fs.existsSync(htaccessPath)) {
+      await common.htaccess.write(tmpDir, spaConfig);
+    }
+  } catch (error) {
+    console.log("SPA included .htaccess file");
```
Comment (sayak-sarkar) [inline packages/api/services/deployService.js:75]: Hey @kunyan This error message seems to be a bit too generic and confusing for me. Can we make it a bit more explicit?

Comment (kunyan) [reply packages/api/services/deployService.js:75]: any suggestion ?

Comment (sayak-sarkar) [reply packages/api/services/deployService.js:73]: Something like what @Jared-Sprague has suggested in his comment.
