### PR TITLE
fix(api): #370 return error if app's user not match

### LINKED ISSUE #370: [Bug]: API broken if a user visit a app which is not belong to
## Describe the bug:

When user request a app which is not created by current user's account.
The API will broken

## Expected behavior:

Return a NotFound or NoAuth error

## Environment;

- Operating System(s): Linux/macOS/Windows [Variant and Version]
- Browser: Firefox/Chrome/Safari [Version] / Other (please specify)

### PR DESCRIPTION
**Pull request by kunyan**
Fix #370

## Screenshot(s)

<details>
<summary>View Screenshots</summary>

</details>

### Ready-for-merge Checklist

- [ ] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [ ] Does the change have appropriate unit tests?
- [ ] Did tests pass?
- [ ] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [ ] Was this feature demo'd and the design review approved?

### CODE REVIEW

File: packages/api/controllers/application.js [hunk 1]
```diff
@@ -13,14 +13,21 @@ module.exports.list = async (req, res, next) => {
...
-  res.send(app);
+  try {
+    const application = await Application.findOne({ name, userId });
+    if (application) {
+      const appPath = application.get("path");
+      const spaDir = common.flatpath.toDir(appPath);
+      const app = await FileService.get(spaDir);
+      return res.send(app);
+    }
+    next(new NotFoundError("Can not found the application you requested"));
```
Comment (sayak-sarkar) [inline packages/api/controllers/application.js:27]: @kunyan I'm thinking that it might be confusing for users if they get this message while trying to access an Apps' details. Maybe another line explaining why they can't see the details would be useful here?

```suggestion
    next(new NotFoundError("Could not find the application you requested. Application details can only be accessed by the uploader."));
```

File: packages/api/controllers/application.test.js [hunk 2]
```diff
@@ -162,6 +163,19 @@ describe("Application Controller", () => {
...
+    expect(fs.existsSync("/fake/webroot/foo")).toBe(true);
+
+    mockingoose(Application).toReturn(null, "findOne");
+
+    const req = mockRequest({ params: { name: "Foo" } });
+    const res = mockResponse();
+    const next = mockNext();
+    await controller.get(req, res, next);
+    expect(next).toHaveBeenCalled();
+    expect(next).toHaveBeenCalledWith(new NotFoundError("Can not found the application you requested"));
```
Comment (sayak-sarkar) [inline packages/api/controllers/application.test.js:176]: As explained above:
```suggestion
    expect(next).toHaveBeenCalledWith(new NotFoundError("Could not find the application you requested. Application details can only be accessed by the uploader."));
```
