### PR TITLE
chore(manager): fix typescript-eslint broken build

### LINKED ISSUE #801: [Bug]: Manager can not build caused by eslint rules upgraded
## Describe the bug:

```
./src/services/APIKeyService.ts
--
  | Line 36:7:  Expected an assignment or function call and instead saw an expression  @typescript-eslint/no-unused-expressions
  |  
  | Search for the keywords to learn more about each error.

```

https://github.com/spaship/spaship/blob/fca86dece6056d5cac61718186e9c715448af3c0/packages/manager/src/services/APIKeyService.ts#L31-L43

It's not recognize the new feature of typescript

There also have some other useless warning

```
Creating an optimized production build...
(node:5418) ExperimentalWarning: Conditional exports is an experimental feature. This feature could change at any time
Compiled with warnings.

./src/index.tsx
  Line 1:8:  'React' was used before it was defined  @typescript-eslint/no-use-before-define

./src/App.tsx
  Line 1:8:  'React' was used before it was defined  @typescript-eslint/no-use-before-define

./src/Routes.tsx
  Line 1:8:  'React' was used before it was defined  @typescript-eslint/no-use-before-define

./src/PrivateRoute.tsx
  Line 1:8:  'React' was used before it was defined  @typescript-eslint/no-use-before-define

./src/components/application/ApplicationList.tsx
  Line 1:8:  'React' was used before it was defined  @typescript-eslint/no-use-before-define

./src/components/application/AddApplication.tsx
  Line 1:8:  'React' was used before it was defined  @typescript-eslint/no-use-before-define

./src/components/application/ApplicationIndex.tsx
  Line 1:8:  'React' was used before it was defined  @typescript-eslint/no-use-before-define

./src/components/user/LoginPage.tsx
  Line 1:8:  'React' was used before it was defined  @typescript-eslint/no-use-before-define

./src/components/authentication/APIKeyList.tsx
  Line 1:8:  'React' was used before it was defined  @typescript-eslint/no-use-before-define

./src/components/environment/EnvironmentList.tsx
  Line 1:8:  'React' was used before it was defined  @typescript-eslint/no-use-before-define

./src/components/dashboard/DashboardIndex.tsx
  Line 1:8:  'React' was used before it was defined  @typescript-eslint/no-use-before-define

./src/components/property/PropertyList.tsx
  Line 1:8:  'React' was used before it was defined  @typescript-eslint/no-use-before-define

./src/components/general/EmptySpinner.tsx
  Line 1:8:  'React' was used before it was defined  @typescript-eslint/no-use-before-define

./src/components/application/ApplicationFilter.tsx
  Line 1:8:  'React' was used before it was defined  @typescript-eslint/no-use-before-define

./src/components/application/ApplicationTable.tsx
  Line 1:8:  'React' was used before it was defined  @typescript-eslint/no-use-before-define

./src/components/application/ApplicationDetail.tsx
  Line 1:8:  'React' was used before it was defined  @typescript-eslint/no-use-before-define

./src/components/authentication/APIKeyTable.tsx
  Line 1:8:  'React' was used before it was defined  @typescript-eslint/no-use-before-define

./src/components/authentication/APIKeyCreateModal.tsx
  Line 1:8:  'React' was used before it was defined  @typescript-eslint/no-use-before-define

./src/components/environment/EnvironmentTable.tsx
  Line 1:8:  'React' was used before it was defined  @typescript-eslint/no-use-before-define

./src/components/property/Property.tsx
  Line 1:8:  'React' was used before it was defined  @typescript-eslint/no-use-before-define

./src/components/property/NewProperty.tsx
  Line 1:8:  'React' was used before it was defined  @typescript-eslint/no-use-before-define

./src/layout/Page.tsx
  Line 1:8:  'React' was used before it was defined  @typescript-eslint/no-use-before-define

./src/layout/Header.tsx
  Line 1:8:  'React' was used before it was defined  @typescript-eslint/no-use-before-define

./src/hooks/useNotify.tsx
  Line 1:8:  'React' was used before it was defined  @typescript-eslint/no-use-before-define

./src/components/application/ApplicationEnvironmentColumn.tsx
  Line 1:8:  'React' was used before it was defined  @typescript-eslint/no-use-before-define

./src/components/general/EmptyNotFound.tsx
  Line 1:8:  'React' was used before it was defined  @typescript-eslint/no-use-before-define

./src/components/application/PrimaryDetails.tsx
  Line 1:8:  'React' was used before it was defined  @typescript-eslint/no-use-before-define

./src/components/application/EnvironmentDetails.tsx
  Line 1:8:  'React' was used before it was defined  @typescript-eslint/no-use-before-define

./src/components/authentication/APIKeySubTable.tsx
  Line 1:8:  'React' was used before it was defined  @typescript-eslint/no-use-before-define

./src/components/property/NewPropertyModal.tsx
  Line 1:8:  'React' was used before it was defined  @typescript-eslint/no-use-before-define

./src/layout/Sidebar.tsx
  Line 1:8:  'React' was used before it was defined  @typescript-eslint/no-use-before-define

./src/layout/PageHeader.tsx
  Line 1:8:  'React' was used before it was defined  @typescript-eslint/no-use-before-define

./src/layout/PageBreadcrumb.tsx
  Line 1:8:  'React' was used before it was defined  @typescript-eslint/no-use-before-define

./src/layout/HeaderTools.tsx
  Line 1:8:  'React' was used before it was defined  @typescript-eslint/no-use-before-define

./src/components/general/Toast.tsx
  Line 1:8:  'React' was used before it was defined  @typescript-eslint/no-use-before-define

./src/components/application/ApplicationEnvironmentTable.tsx
  Line 1:8:  'React' was used before it was defined  @typescript-eslint/no-use-before-define

./src/components/general/Spinner.tsx
  Line 1:8:  'React' was used before it was defined  @typescript-eslint/no-use-before-define

./src/components/general/ConfirmButton.tsx
  Line 1:8:  'React' was used before it was defined  @typescript-eslint/no-use-before-define

./src/layout/PageNav.tsx
  Line 1:8:  'React' was used before it was defined  @typescript-eslint/no-use-before-define

./src/layout/Namespace.tsx
  Line 1:8:  'React' was used before it was defined  @typescript-eslint/no-use-before-define

./src/layout/UserStatus.tsx
  Line 1:8:  'React' was used before it was defined  @typescript-eslint/no-use-before-define

```

## Environment;

- Operating System(s): Linux/macOS/Windows [Variant and Version]
- Browser: Firefox/Chrome/Safari [Version] / Other (please specify)

## Additional context

Related Issue: https://github.com/typescript-eslint/typescript-eslint/issues/2540

### PR DESCRIPTION
**Pull request by kunyan**
## Closes / Fixes / Resolves

Fix #801 

## Screenshot(s)

<details>
<summary>View Screenshots</summary>

</details>

### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [ ] Does the change have appropriate unit tests?
- [ ] Did tests pass?
- [ ] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [ ] Was this feature demo'd and the design review approved?

### CODE REVIEW

File: packages/manager/src/services/APIKeyService.ts [hunk 1]
```diff
@@ -33,12 +33,14 @@ export const createMultiAPIKeys = async (environments: IEnvironment[], payload:
     if (envKey) {
       apiKey.label = envKey.label;
       apiKey.expiredDate = envKey.expiredDate;
-      apiKey.environments?.push({
-        name: env.name,
-        key: envKey.key,
-        shortKey: envKey.shortKey,
-        createdAt: envKey.createdAt,
-      });
+      if (!!apiKey.environments) {
```
Comment (sayak-sarkar) [inline packages/manager/src/services/APIKeyService.ts:36]: Isn't this the same as:
```suggestion
      if (apiKey.environments) {
```

**Review by sayak-sarkar — CHANGES_REQUESTED** [review]

File: packages/manager/src/services/APIKeyService.ts (hunk 1 above)
Comment (mwcz) [reply packages/manager/src/services/APIKeyService.ts:36]: Yes, and since environments is an array (I think?), `.length` needs to be checked, because empty arrays coerce to `true`.  See:

```js
let x = [];
if (x) console.log("x is true")
>>> x is true
```

**Review by sayak-sarkar — APPROVED** [review]
