### PR TITLE
fix(#367): Fixed multiple minor styling issues across Manager components.

### LINKED ISSUE #367: [Bug]: UI layout has multiple inconsistencies from Manager design
## Describe the bug:
There are multiple minor styling inconsistencies within the SPA Manager UI pages for Application and Authentication.

## Additional context
Some of the obvious deviations from the design are:
- [x] Toolbar alignment across the Application and Authentication pages.
- [x] Alignment of EmptyTable message for ApplicationTable.
- [x] Alignment of EmptyTable message for APIKeyTable.
- [x] Typo in the Dashboard's Coming Soon message.

### PR DESCRIPTION
**Pull request by sayak-sarkar**
## Closes / Fixes / Resolves
Fixes #367 

## Explain the feature/fix
Fixed the following issues:
- Toolbar alignment across the Application and Authentication pages.
- Alignment of EmptyTable message for ApplicationTable.
- Alignment of EmptyTable message for APIKeyTable.
- Typo in the Dashboard's Coming Soon message.

## Does this PR introduce a breaking change
No

## Screenshot(s)

<details>
<summary>View Screenshots</summary>
image
image
image
</details>

### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [x] Did tests pass?

### CODE REVIEW

File: packages/manager/src/components/authentication/APIKeyTable.tsx [hunk 1]
```diff
@@ -99,12 +99,12 @@ export default (props: IProps) => {
             heightAuto: true,
             cells: [
               {
-                props: { colSpan: 2 },
+                props: { colSpan: 3 },
```
Comment (kunyan) [inline packages/manager/src/components/authentication/APIKeyTable.tsx:102]: Good catch !
